

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/Tirocinio/instance
    environment:
      - FLASK_ENV=development
    depends_on:
      - node-red

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-docker/data:/data
    restart: unless-stopped
