DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  password TEXT,
  privilegies INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);